// <auto-generated />
namespace BestApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class F18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(F18));
        
        string IMigrationMetadata.Id
        {
            get { return "201911200947275_F18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
